title                       : Bioinformatics  # The title of the book. Will be placed in the left navbar.
author                      : Christian Kruse  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo
only_build_toc_files        : false